"""initial migration

Revision ID: 8747157ea93e
Revises: 
Create Date: 2025-05-03 02:16:57.881302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8747157ea93e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('journal', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('impact_factor', sa.Float(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('digest_papers',
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digest.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('digest_id', 'paper_id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_doi', sa.String(length=100), nullable=False),
    sa.Column('vote', sa.String(length=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('used_for_prefs', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['paper_doi'], ['paper.doi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('digest_papers')
    op.drop_table('paper')
    op.drop_table('digest')
    # ### end Alembic commands ###
